"""Prebuilt native runtime for the ProtoDUNE conditions client.

Contains the self-contained ``fn-fileget`` executable (statically linked
against libfrontier_client and OpenSSL, RPATH ``$ORIGIN``), its PAC support
library ``libpacparser.so.1``, and the ``frontier-manifest.json`` provenance
record produced by ``scripts/build-frontier-client.sh``.

This package is a build artifact: the binary files are generated by CI and
gitignored, never committed. ``pd_cds_api.state.ApiClientState`` resolves the
executable from here via ``importlib.resources``.
"""
