[project]
name = "pd-cds"
version = "0.1.1"
description = "ProtoDUNE Conditions Data Service"
readme = "README.md"
authors = [{ name = "Mike Clymer", email = "mike.clymer@colostate.edu" }]
requires-python = ">=3.14"
dependencies = ["pd-cds-cli"]

[tool.uv.sources]
pd-cds-cli = { workspace = true }

[tool.uv.workspace]
members = ["client/*"]

[project.scripts]
pd-cds = "pd_cds_cli.main:app"

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [{ include-group = "lint" }, { include-group = "test" }]
lint = ["ruff>=0.14.10"]
test = ["locust>=2.43.0"]
