[project]
name = "protodune-conditions"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Mike Clymer", email = "mike.clymer@colostate.edu" }]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.5",
    "typer>=0.21.1",
]

[project.scripts]
pd-cdb = "protodune_conditions.main:app"
# locust = "locust -f tests/perf/locustfile.py"

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [{ include-group = "lint" }, { include-group = "test" }]
lint = ["ruff>=0.14.10"]
test = ["locust>=2.43.0"]
