[dune_runcon_prod]
LongCacheExpireSeconds: 300
ShortCacheExpireSeconds: 300
MaxDbAcquireSeconds: 300
MaxThreads: 5
FileBaseDirectory: http://condb2-rest-api:8888/dune_runcon_prod/
# FileBaseDirectory: https://dbdata0vm.fnal.gov:9443/dune_runcon_prod/