[dune_runcon_prod]
LongCacheExpireSeconds: 300
ShortCacheExpireSeconds: 300
MaxDbAcquireSeconds: 300
MaxThreads: 5
FileBaseDirectory: http://<CONDB2_SERVICE_URL>:<CONDB2_SERVICE_PORT>/dune_runcon_prod/
