[dune_runcon_prod]
ValidateLastModifiedSeconds: 300
MaxDbExecuteSeconds: 30
MaxThreads: 200
LongCacheExpireSeconds: 21000
ShortCacheExpireSeconds: 21000
FileBaseDirectory: http://<CONDB2_SERVICE_URL>:<CONDB2_SERVICE_PORT>/dune_runcon_prod/
