name: frontier-condb2

services:
  frontier-server:
    container_name: frontier-server
    build: containers/frontier_server
    image: frontier-server
    ports:
      - "8000:8000"
    depends_on:
      - condb2-rest-api

  condb2-rest-api:
    container_name: condb2-rest-api
    build: containers/condb2_rest_api
    image: condb2-rest-api
