[uwsgi]
http = :<CONDB2_SERVICE_PORT>
logger = file:<APP_STORAGE>/logs/condb2/uwsgi.log
manage-script-name = true
mount = /dune_runcon_prod=ServerApp.py
buffer-size = 32768

enable-threads = true
vacuum = true
single-interpreter = true
die-on-term = true
need-app = true

disable-logging = true
log-4xx = true
log-5xx = true

processes = 2
lazy-apps = true

thunder-lock = true

max-worker-lifetime = 600
harakiri = 60

log-x-forwarded-for = true

log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)" in %(msecs)ms
