"""Generate Zensical API reference pages for the client packages.

Zensical 0.0.69's native mkdocstrings does not cascade ``members`` into
nested classes, so pydantic ``Field(description=…)`` metadata only renders
when a directive targets the class directly — module-granularity plugins
like ``api-autonav`` therefore lose the field docs. This script (the
pattern Zensical documents for replacing ``gen-files``) walks the public
API of ``pd_cds_api`` and ``pd_cds_cli`` and writes one page per module
under ``docs/reference/``::

    ::: <module>            # module docstring only (members: false)
    ::: <module>.<Class>    # full member detail (members: true)

Generated files are committed; run ``make docs-gen`` after adding or
renaming public classes/functions, and CI (``--check``) fails if the tree
drifts from the sources. Stdlib-only.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGES = [
    ("pd_cds_api", ROOT / "client" / "pd-cds-api" / "src" / "pd_cds_api"),
    ("pd_cds_cli", ROOT / "client" / "pd-cds-cli" / "src" / "pd_cds_cli"),
]
OUTPUT_DIR = ROOT / "docs" / "reference"
HEADER = (
    "<!-- Generated by scripts/gen_api_reference.py — do not edit. "
    "Run `make docs-gen`; CI verifies with --check. -->\n"
)


def find_modules(pkg_name: str, pkg_dir: Path) -> list[str]:
    """List dotted module paths of a package, ``__init__`` first.

    Args:
        pkg_name: Top-level package import name.
        pkg_dir: Directory containing the package sources.

    Returns:
        Dotted names in stable traversal order.
    """
    modules = [pkg_name]
    for path in sorted(pkg_dir.rglob("*")):
        if path.is_file() and path.suffix == ".py" and path.name != "__init__.py":
            rel = path.relative_to(pkg_dir).with_suffix("")
            modules.append(".".join([pkg_name, *rel.parts]))
        elif path.is_dir() and (path / "__init__.py").is_file():
            rel = path.relative_to(pkg_dir)
            modules.append(".".join([pkg_name, *rel.parts]))
    return modules


def public_members(module_path: Path) -> list[tuple[str, str]]:
    """Scan a module's top level for public classes and functions.

    Args:
        module_path: The ``.py`` file to parse.

    Returns:
        ``(dotted_suffix, kind)`` pairs in source order; kind is
        ``"class"`` or ``"function"``. Imports, privates and dunders are
        skipped.
    """
    tree = ast.parse(module_path.read_text(encoding="utf-8"))
    members: list[tuple[str, str]] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            members.append((node.name, "class"))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                members.append((node.name, "function"))
    return members


def module_file(pkg_dir: Path, pkg_name: str, dotted: str) -> Path:
    """Resolve a dotted module name to its source file.

    Args:
        pkg_dir: Package source directory.
        pkg_name: Top-level package name (for the ``__init__`` case).
        dotted: Dotted module path.

    Returns:
        Path to the ``.py`` file implementing the module.
    """
    if dotted == pkg_name:
        return pkg_dir / "__init__.py"
    candidate = pkg_dir / dotted.removeprefix(f"{pkg_name}.").replace(".", "/")
    return candidate / "__init__.py" if candidate.is_dir() else candidate.with_suffix(".py")


def render_page(dotted: str, members: list[tuple[str, str]]) -> str:
    """Render one reference page for a module.

    Args:
        dotted: Dotted module path (also the page title).
        members: Public top-level members from :func:`public_members`.

    Returns:
        Full Markdown source for the page.
    """
    lines = [
        "---",
        f"title: {dotted}",
        "---",
        "",
        HEADER,
        f"::: {dotted}",
        "    options:",
        "      members: false",
    ]
    for name, kind in members:
        lines.append("")
        lines.append(f"::: {dotted}.{name}")
        lines.append("    options:")
        lines.append("      heading_level: 2")
        if kind == "class":
            lines.append("      members: true")
    return "\n".join(lines) + "\n"


def generate() -> dict[Path, str]:
    """Build the full reference tree as ``path -> content`` pairs.

    Returns:
        Mapping of output file paths to their generated Markdown.
    """
    pages: dict[Path, str] = {}
    for pkg_name, pkg_dir in PACKAGES:
        for dotted in find_modules(pkg_name, pkg_dir):
            src = module_file(pkg_dir, pkg_name, dotted)
            members = public_members(src) if src.is_file() else []
            pages[OUTPUT_DIR / f"{dotted}.md"] = render_page(dotted, members)
    return pages


def nav_entries() -> list[str]:
    """List generated page paths (relative to docs_dir) for zensical.toml.

    Returns:
        POSIX-style relative paths in generation order.
    """
    return [f"reference/{path.name}" for path in generate()]


def main(argv: list[str] | None = None) -> int:
    """Write (default) or check (``--check``) the generated tree.

    Args:
        argv: Argument vector override.

    Returns:
        0 when in sync / written; 1 when ``--check`` finds drift.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 (listing diffs) if committed pages differ",
    )
    args = parser.parse_args(argv)
    pages = generate()

    if args.check:
        problems: list[str] = []
        for path, content in pages.items():
            if not path.exists():
                problems.append(f"missing: {path.relative_to(ROOT)}")
            elif path.read_text(encoding="utf-8") != content:
                diff = difflib.unified_diff(
                    path.read_text(encoding="utf-8").splitlines(),
                    content.splitlines(),
                    lineterm="",
                    n=1,
                )
                problems.append(f"stale: {path.relative_to(ROOT)}\n" + "\n".join(diff))
        stale_extra = [
            p for p in OUTPUT_DIR.glob("*.md") if p not in pages
        ] if OUTPUT_DIR.is_dir() else []
        for extra in sorted(stale_extra):
            problems.append(f"orphan (no matching module): {extra.relative_to(ROOT)}")
        if problems:
            print("docs/reference/ is out of sync:\n" + "\n".join(problems),
                  file=sys.stderr)
            print("fix with: make docs-gen", file=sys.stderr)
            return 1
        print(f"docs/reference/ in sync ({len(pages)} pages)")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in pages.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    print(f"nav hint: {', '.join(nav_entries())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
