name: Build and Push Podman Images

on:
  push:
    # branches:
    # - main

  pull_request:

env:
  REGISTRY: ghcr.io
  SERVICES: "condb2-rest-api frontier-server"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
      options: --privileged

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install podman and podman-compose
        shell: bash
        run: |
          dnf update -y
          dnf install epel-release -y
          dnf install podman podman-compose -y

      - name: Log in to the Container Registry
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ${{ env.REGISTRY }} \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Build images with podman-compose
        shell: bash
        run: |
          podman-compose -f infra/compose.yml build --pull

      - name: Tag and push images to GHCR
        shell: bash
        run: |
          for SERVICE in ${{ env.SERVICES }}; do
            IMAGE_NAME=`echo "${{ env.REGISTRY }}/${{ github.repository }}:${SERVICE}-${{ github.sha }}" | tr '[:upper:]' '[:lower:]'`
            echo "Tagging and pushing ${SERVICE} as ${IMAGE_NAME}"
            podman tag ${SERVICE} ${IMAGE_NAME}
            podman push ${IMAGE_NAME}
            podman rmi ${IMAGE_NAME}
          done
