name: Build and Push Podman Images

on:
  push:
    # branches:
    #   - main
    #   - 18-containerize-frontier-condb2

  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install podman and podman-compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman podman-compose

      # - name: Log in to the Container Registry
      #   uses: docker/login-action@v4
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container Registry
        run: podman login -v -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push images with podman-compose
        id: push
        run: podman-compose -f infra/compose.yml build push
