name: Build and Push Podman Images

on:
  push:
    branches:
      # - main
      - 18-containerize-frontier-condb2

  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    container: almalinux:9

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install podman and podman-compose
        shell: bash
        run: |
          sudo mount -o remount,shared / /
          sudo dnf update -y
          sudo dnf install epel-release -y
          sudo dnf install -y podman podman-compose

      # - name: Log in to the Container Registry
      #   uses: docker/login-action@v4
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container Registry
        shell: bash
        run: sudo podman login -v -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v6
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push images with podman-compose
        id: push
        shell: bash
        run: |
          sudo podman-compose -f infra/compose.yml build --pull
          sudo podman-compose -f infra/compose.yml push
