name: Release

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - "v*" # Trigger on semver tags like v0.1.0, v2.2.3, etc.

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-upload-container-artifacts:
    uses: ./.github/workflows/containers-ci.yml
    secrets: inherit

  server-release:
    needs: build-and-upload-container-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create server-dist directory
        run: mkdir -p server-dist

      - name: Download Quadlet artifacts
        uses: actions/download-artifact@v8
        with:
          name: quadlet-artifacts-${{ github.ref_name }}
          path: server-dist/
          skip-decompress: true

      - name: Create server release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Short branch or tag name that triggered the workflow run.
          # Releases
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            ./server-dist/*.zip \
            --repo="$GITHUB_REPOSITORY" \
            --title="${TAG#v}" \
            --generate-notes
