name: Release

on:
  push:
    branches:
      # - main
      - 32-cicd-quadlet-artifact-release

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  read-release-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            VERSION

      - name: Read VERSION file
        id: release-version
        run: echo "RELEASE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

  build-and-upload-container-artifacts:
    needs: read-release-version
    uses: ./.github/workflows/server.yml
    with:
      release-version: "${{ github.env.RELEASE_VERSION }}"
    secrets: inherit

  server-release:
    needs: build-and-upload-container-artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Create server-dist directory
        run: mkdir -p server-dist

      - name: Download Quadlet artifacts
        uses: actions/download-artifact@v8
        with:
          name: "quadlet-artifacts-v$RELEASE_VERSION"
          path: server-dist/
          skip-decompress: true

      - name: Create server release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TAG: "v$RELEASE_VERSION"
        run: |
          gh release create "$TAG" \
            ./server-dist/*.zip \
            --repo="$GITHUB_REPOSITORY" \
            --title="${RELEASE_VERSION}" \
            --generate-notes

  tag-release-version:
    needs: server-release
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: |
          dnf update -y
          dnf install git -y

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Tag release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "v$RELEASE_VERSION" \
            -m "Release v$RELEASE_VERSION"
          git push origin "v$RELEASE_VERSION"

      # run: |
      #   git config --global --add safe.directory $PWD
      #   git config user.name "${{ github.actor }}"
      #   git config user.email "${{ github.actor }}"
      #   git tag -a "v$RELEASE_VERSION" \
      #     -m "Release v$RELEASE_VERSION"
      #   git push origin "v$RELEASE_VERSION"
